name: PlayerCorpses
version: "1.0.0"
main: io.greitan.avion.PlayerCorpses
description: Add corpses to your server
api-version: "1.21.4"
author: Greitan.IO
folia-supported: true

dependencies:
  server:
    FancyNpcs:
      load: BEFORE
      required: true
